# Generated by Django 4.0.2 on 2022-02-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_income_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='source',
            field=models.CharField(default='nosource', max_length=100),
        ),
    ]
