# Generated by Django 4.0.2 on 2022-02-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='type',
            field=models.CharField(default='expense', max_length=10),
        ),
    ]
