# Generated by Django 4.0.2 on 2022-02-15 15:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('balance', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.localtime)),
            ],
        ),
    ]
